package com.example.simplegolf;

import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.ViewModelProvider;

import com.example.simplegolf.model.Course;
import com.example.simplegolf.model.Player;
import com.example.simplegolf.model.Repository;
import com.example.simplegolf.model.Scorecard;
import com.example.simplegolf.model.Tee;
import com.example.simplegolf.ui.playerSelect.PlayerSelectDialogue;
import com.example.simplegolf.ui.playerSelect.PlayerSelectViewModel;

public class PlayerSelectActivity extends AppCompatActivity implements PlayerSelectDialogue.DialogListener {

    private PlayerSelectViewModel viewModel;
    private LinearLayout playerList;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_select_player);
        viewModel = new ViewModelProvider(this).get(PlayerSelectViewModel.class);

        if (getIntent().hasExtra("course")) {
            Course course = (Course) getIntent().getSerializableExtra("course");
            viewModel.setCourse(course);
        }
        playerList = findViewById(R.id.playerList);
    }

    public void showDialog(View view) {
        PlayerSelectDialogue playerSelectDialogue = new PlayerSelectDialogue();
        playerSelectDialogue.show(getSupportFragmentManager(), "game activity dialog");
    }

    public void onClickCreate(View view) {
        Scorecard scorecard = viewModel.buildScorecard();

        // Save to DB and fetch to get correct ID, allows course to be updated/saved in the future.
        new Thread(() -> {
            Repository repository = Repository.getRepository(this);

            long scoreCardId = repository.getDb().scorecardDAO().insert(scorecard); // Save to DB
            Scorecard savedScorecard = repository.getDb().scorecardDAO().getById(scoreCardId); // Fetch from DB to include the new autogenerated ID.

            runOnUiThread(() -> { // Start activity after DB operations are done.
                Intent startGame = new Intent(getApplicationContext(), GameActivity.class);
                startGame.putExtra("scorecard", savedScorecard);
                startActivity(startGame);
            });
        }).start();
    }


    @Override
    public void applyPlayerInfo(String name, String abbr, double HCP, String tee) {
        Course course = viewModel.getCourse();

        Tee temp = null;
        for (Tee x : course.getTees()) {
            if (x.getName().equals(tee))
                temp = x;
        }

        viewModel.addPlayer(new Player(name, abbr, course, temp, HCP));

        TextView tv = new TextView(this);
        tv.setText(name);
        tv.setGravity(Gravity.CENTER_VERTICAL | Gravity.CENTER_HORIZONTAL);
        tv.setTextSize(40);

        playerList.addView(tv);
    }
}
